print('Hello world')
print('What day is today')
print('Tomorrom will be the first Zoom online class') 
print('Why I cannot see the changes')
print('I am verying whether I got the git and gihub for VScode')